// resources/js/Components/invitation/templates/scene/configs/BeachConfig.js
export default {
    background: '/images/templates/beach/scene.webp',
    fallbackBg: 'linear-gradient(180deg, #87CEEB 0%, #F0E68C 60%, #DEB887 100%)',
    hotspots: [
        {
            id:           'gallery',
            x: 18, y: 12,
            label:        'Gallery',
            section:      'gallery',
            illustration: '/images/templates/beach/objects/gallery-board.png',
            animation:    'sway',
            size:         80,
        },
        {
            id:           'date_venue',
            x: 55, y: 10,
            label:        'Date & Venue',
            section:      'events',
            illustration: '/images/templates/beach/objects/date-sign.png',
            animation:    'sway',
            size:         72,
        },
        {
            id:           'about',
            x: 45, y: 38,
            label:        'About Us',
            section:      'couple',
            illustration: '/images/templates/beach/objects/couple.png',
            animation:    'float',
            size:         90,
        },
        {
            id:           'love_story',
            x: 52, y: 55,
            label:        'Love Story',
            section:      'love_story',
            illustration: '/images/templates/beach/objects/bottle.png',
            animation:    'float',
            size:         56,
        },
        {
            id:           'rsvp',
            x: 72, y: 50,
            label:        'RSVP',
            section:      'rsvp',
            illustration: '/images/templates/beach/objects/mailbox.png',
            animation:    'bounce',
            size:         64,
        },
        {
            id:           'gift',
            x: 68, y: 72,
            label:        'Gift',
            section:      'gift',
            illustration: '/images/templates/beach/objects/chest.png',
            animation:    'pulse',
            size:         68,
        },
    ],
}
