// resources/js/Components/invitation/templates/scene/configs/GardenConfig.js
export default {
    background: '/images/templates/garden/scene.webp',
    fallbackBg: 'linear-gradient(180deg, #E8F5E9 0%, #C8E6C9 40%, #A5D6A7 100%)',
    hotspots: [
        {
            id:           'gallery',
            x: 20, y: 15,
            label:        'Gallery',
            section:      'gallery',
            illustration: '/images/templates/garden/objects/gallery-easel.png',
            animation:    'sway',
            size:         76,
        },
        {
            id:           'date_venue',
            x: 60, y: 12,
            label:        'Date & Venue',
            section:      'events',
            illustration: '/images/templates/garden/objects/gate-sign.png',
            animation:    'sway',
            size:         70,
        },
        {
            id:           'about',
            x: 50, y: 40,
            label:        'About Us',
            section:      'couple',
            illustration: '/images/templates/garden/objects/couple.png',
            animation:    'float',
            size:         90,
        },
        {
            id:           'love_story',
            x: 30, y: 55,
            label:        'Love Story',
            section:      'love_story',
            illustration: '/images/templates/garden/objects/diary.png',
            animation:    'pulse',
            size:         58,
        },
        {
            id:           'rsvp',
            x: 70, y: 52,
            label:        'RSVP',
            section:      'rsvp',
            illustration: '/images/templates/garden/objects/birdbath.png',
            animation:    'bounce',
            size:         64,
        },
        {
            id:           'gift',
            x: 65, y: 70,
            label:        'Gift',
            section:      'gift',
            illustration: '/images/templates/garden/objects/basket.png',
            animation:    'float',
            size:         68,
        },
    ],
}
