// resources/js/Components/invitation/templates/scene/configs/GardenConfig.js
export default {
    background:  '/images/templates/garden/scene.webp',
    fallbackBg:  'linear-gradient(180deg, #E8F5E9 0%, #C8E6C9 40%, #A5D6A7 100%)',
    modalTheme:  'parchment',
    hotspots: [
        {
            id:           'gallery',
            x: 25, y: 23,
            label:        'Gallery',
            section:      'gallery',
            illustration: '/images/templates/garden/objects/polaroid.png',
            animation:    'pulse',
            size:         76,
        },
        {
            id:           'date_venue',
            x: 72, y: 11.7,
            label:        'Date & Venue',
            section:      'events',
            illustration: '/images/templates/garden/objects/papan2.png',
            animation:    'swing',
            size:         70,
        },
        {
            id:           'about',
            x: 60, y: 45,
            label:        'About Us',
            section:      'couple',
            illustration: '/images/templates/garden/objects/couple.png',
            animation:    'float',
            size:         170,
        },
        {
            id:           'love_story',
            x: 33, y: 60,
            label:        'Love Story',
            section:      'love_story',
            illustration: '/images/templates/garden/objects/diary.png',
            animation:    'pulse',
            size:         125,
        },
        {
            id:           'rsvp',
            x: 85, y: 63,
            label:        'RSVP',
            section:      'rsvp',
            illustration: '/images/templates/garden/objects/letter.png',
            animation:    'pulse-strong',
            size:         64,
        },
        {
            id:           'gift',
            x: 85, y: 88,
            label:        'Gift',
            section:      'gift',
            illustration:  '/images/templates/garden/objects/basket.png',
            animation:     'float',
            size:          150,
            labelPosition: 'top',
        },
    ],
}
